/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.KhachHangDao;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.KhachHang;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Administrator
 */
public class KhachHangJPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhachHangJPanel
     */
    DefaultTableModel model = new DefaultTableModel();

    public KhachHangJPanel() {
        initComponents();

        jtbKhachHang.getTableHeader().setBackground(new Color(0, 113, 61));
        jtbKhachHang.getTableHeader().setForeground(Color.white);
        jtbKhachHang.setFont(new Font("Times New Roman", Font.PLAIN, 15));
        jtbKhachHang.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 17));
        jtbKhachHang.getTableHeader().setPreferredSize(new Dimension(100, 35));
        jtbKhachHang.setRowHeight(35);

        addPlaceholderStyle(jtfTimKiem);

        layDuLieuTable();
        sort();

    }

    public void layDuLieuTable() {
        List<KhachHang> listKhachHang = new KhachHangDao().getList();
        model = (DefaultTableModel) jtbKhachHang.getModel();
        model.setRowCount(0);
        for (KhachHang i : listKhachHang) {
            model.addRow(new Object[]{
                i.getMaKhachHang(),
                i.getHoTen(),
                i.getNgaySinh(),
                i.getGioiTinh(),
                i.getDienThoai()
            });
        }
    }

    public static void hienThiTable() {
        DefaultTableModel model = new DefaultTableModel();
        List<KhachHang> listKhachHang = new KhachHangDao().getList();
        model = (DefaultTableModel) jtbKhachHang.getModel();
        model.setRowCount(0);
        for (KhachHang i : listKhachHang) {
            model.addRow(new Object[]{
                i.getMaKhachHang(),
                i.getHoTen(),
                i.getNgaySinh(),
                i.getGioiTinh(),
                i.getDienThoai()
            });
        }
    }

    public void sort() {
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>(model);
        jtbKhachHang.setRowSorter(rowSorter);
    }

    public void search() {
        model = (DefaultTableModel) jtbKhachHang.getModel();
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>(model);
        jtbKhachHang.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + jtfTimKiem.getText()));
    }

    public void addPlaceholderStyle(JTextField jTextField) {
        Font font = jTextField.getFont();
        font = font.deriveFont(Font.ITALIC);
        jTextField.setFont(font);
        jTextField.setForeground(Color.GRAY);
    }

    public void removePlaceholderStyle(JTextField jTextField) {
        Font font = jTextField.getFont();
        font = font.deriveFont(Font.PLAIN);
        jTextField.setFont(font);
        jTextField.setForeground(Color.BLACK);
    }

    public void hienThongTin(KhachHangJFrame khachHangJFrame, int row) {
        List<KhachHang> listKhachHang = new KhachHangDao().getList();
        KhachHang khachHang = listKhachHang.get(row);

        khachHangJFrame.setTitle("Thông tin nhân viên");
        khachHangJFrame.setVisible(true);
        khachHangJFrame.setResizable(false);
        khachHangJFrame.setLocationRelativeTo(null);

        khachHangJFrame.select(khachHang);
    }

    public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException ioe) {
            System.out.println(ioe);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbDanhSachKhachHang = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        jbnThem = new javax.swing.JButton();
        jbnSua = new javax.swing.JButton();
        jbnXoa = new javax.swing.JButton();
        jpnView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbKhachHang = new javax.swing.JTable();
        jbnXuatBaoCao = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 700));

        jlbDanhSachKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        jlbDanhSachKhachHang.setFont(new java.awt.Font("Sitka Text", 1, 29)); // NOI18N
        jlbDanhSachKhachHang.setForeground(new java.awt.Color(0, 113, 61));
        jlbDanhSachKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDanhSachKhachHang.setText("DANH SÁCH KHÁCH HÀNG");
        jlbDanhSachKhachHang.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jtfTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jtfTimKiem.setText("Tìm kiếm");
        jtfTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfTimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfTimKiemFocusLost(evt);
            }
        });
        jtfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTimKiemKeyReleased(evt);
            }
        });

        jbnThem.setBackground(new java.awt.Color(157, 205, 239));
        jbnThem.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jbnThem.setText("Thêm");
        jbnThem.setToolTipText("");
        jbnThem.setBorder(null);
        jbnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnThemActionPerformed(evt);
            }
        });

        jbnSua.setBackground(new java.awt.Color(157, 205, 239));
        jbnSua.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jbnSua.setText("Sửa");
        jbnSua.setBorder(null);
        jbnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnSuaActionPerformed(evt);
            }
        });

        jbnXoa.setBackground(new java.awt.Color(157, 205, 239));
        jbnXoa.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jbnXoa.setText("Xóa");
        jbnXoa.setBorder(null);
        jbnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnXoaActionPerformed(evt);
            }
        });

        jpnView.setBackground(new java.awt.Color(255, 255, 255));

        jtbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ và tên", "Ngày sinh", "Giới tính", "Điện thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbKhachHang);

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        jbnXuatBaoCao.setBackground(new java.awt.Color(157, 205, 239));
        jbnXuatBaoCao.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jbnXuatBaoCao.setText("Xuất Báo Cáo");
        jbnXuatBaoCao.setBorder(null);
        jbnXuatBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnXuatBaoCaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbnXuatBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbDanhSachKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jtfTimKiem)
                                .addGap(110, 110, 110)
                                .addComponent(jbnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpnView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDanhSachKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbnXuatBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnThemActionPerformed
        KhachHangJFrame khachHangJFrame = new KhachHangJFrame();
        khachHangJFrame.setTitle("Thông tin khách hàng");
        khachHangJFrame.setVisible(true);
        khachHangJFrame.setResizable(false);
        khachHangJFrame.setLocationRelativeTo(null);
        khachHangJFrame.jbnXoa.setVisible(false);
        khachHangJFrame.jbnLuu.setText("Thêm");
        khachHangJFrame.jbnLuu.setVisible(true);
        khachHangJFrame.jtfMaKhachHang.setEditable(true);
    }//GEN-LAST:event_jbnThemActionPerformed

    private void jtfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTimKiemKeyReleased
        search();
    }//GEN-LAST:event_jtfTimKiemKeyReleased

    private void jtbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbKhachHangMouseClicked
        KhachHangJFrame khachHangJFrame = new KhachHangJFrame();
        int row = jtbKhachHang.getSelectedRow();
        if (evt.getClickCount() == 2) {
            hienThongTin(khachHangJFrame, row);
        }
    }//GEN-LAST:event_jtbKhachHangMouseClicked

    private void jtfTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfTimKiemFocusGained
        if (jtfTimKiem.getText().equals("Tìm kiếm")) {
            jtfTimKiem.setText(null);
            jtfTimKiem.requestFocus();
            removePlaceholderStyle(jtfTimKiem);
        }
    }//GEN-LAST:event_jtfTimKiemFocusGained

    private void jtfTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfTimKiemFocusLost
        if (jtfTimKiem.getText().length() == 0) {
            addPlaceholderStyle(jtfTimKiem);
            jtfTimKiem.setText("Tìm kiếm");
        }
    }//GEN-LAST:event_jtfTimKiemFocusLost

    private void jbnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnSuaActionPerformed
        KhachHangJFrame khachHangJFrame = new KhachHangJFrame();
        int row = jtbKhachHang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng cần cập nhật!");
        } else {
            hienThongTin(khachHangJFrame, row);
            khachHangJFrame.jbnXoa.setVisible(false);
        }
    }//GEN-LAST:event_jbnSuaActionPerformed

    private void jbnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnXoaActionPerformed
        KhachHangJFrame khachHangJFrame = new KhachHangJFrame();
        int row = jtbKhachHang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng cần xóa!");
        } else {
            khachHangJFrame.delete(jtbKhachHang.getValueAt(row, 0).toString());
        }
    }//GEN-LAST:event_jbnXoaActionPerformed

    private void jbnXuatBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnXuatBaoCaoActionPerformed
        try {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();

            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                XSSFWorkbook wb = new XSSFWorkbook();
                XSSFSheet sheet = wb.createSheet("Khách Hàng");

                XSSFRow row = null;
                Cell cell = null;

                row = sheet.createRow((short) 1);
                row.setHeight((short) 500);
                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue("DANH SÁCH KHÁCH HÀNG");

                row = sheet.createRow((short) 3);
                row.setHeight((short) 500);
                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue("Mã khách hàng");
                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue("Họ và tên");
                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue("Ngày sinh");
                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue("Giới tính");
                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue("Điện thoại");
                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue("Địa chỉ");

                List<KhachHang> listKhachHang = new KhachHangDao().getList();

                for (int i = 0; i < listKhachHang.size(); i++) {
                    KhachHang khachHang = listKhachHang.get(i);
                    row = sheet.createRow((short) 4 + i);
                    row.setHeight((short) 400);
                    row.createCell(0).setCellValue(khachHang.getMaKhachHang());
                    row.createCell(1).setCellValue(khachHang.getHoTen());
                    row.createCell(2).setCellValue(khachHang.getNgaySinh().toString());
                    row.createCell(3).setCellValue(khachHang.getGioiTinh());
                    row.createCell(4).setCellValue(khachHang.getDienThoai());
                    row.createCell(5).setCellValue(khachHang.getDiaChi());
                }

                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(saveFile.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Không thể tạo file");
            }
        } catch (FileNotFoundException e) {
            System.out.println(e);
        } catch (IOException io) {
            System.out.println(io);
        }
    }//GEN-LAST:event_jbnXuatBaoCaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnSua;
    private javax.swing.JButton jbnThem;
    private javax.swing.JButton jbnXoa;
    private javax.swing.JButton jbnXuatBaoCao;
    private javax.swing.JLabel jlbDanhSachKhachHang;
    private javax.swing.JPanel jpnView;
    private static javax.swing.JTable jtbKhachHang;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables
}
